[versions]

android-plugin = '8.8.0'

android-sdk-compile = '35'
android-sdk-min = '26'
android-sdk-target = '35'

androidx-activity = '1.10.0'
androidx-compose-bom = '2025.01.00'

java = '17'

kotlin = '2.1.0'


[libraries]

androidx-activity = { module = 'androidx.activity:activity', version.ref = 'androidx-activity' }
androidx-compose-activity = { module = 'androidx.activity:activity-compose', version.ref = 'androidx-activity' }
androidx-compose-bom = { module = 'androidx.compose:compose-bom-alpha', version.ref = 'androidx-compose-bom' }
androidx-compose-foundation = { module = 'androidx.compose.foundation:foundation' }
androidx-compose-material = { module = 'androidx.compose.material3:material3' }
androidx-compose-runtime = { module = 'androidx.compose.runtime:runtime' }
androidx-compose-ui = { module = 'androidx.compose.ui:ui' }


[plugins]

android-application = { id = 'com.android.application', version.ref = 'android-plugin' }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
